spring:
  data:
    mongodb:
      port: '27017'
      username: myUserAdmin
      password: admin
      uri: mongodb://localhost:27017/gestion-stock
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG